### ISSUE TITLE
Request to add a software usage license to this project

### ISSUE THREAD

**Issue by jonnybach** [realeyes-media/scte35-swift#4]
I am a current employee of Comcast VIPER that would like to contribute and integrate this super cool SCTE35 parser into a framework we develop for the Comcast Stream iOS app.

I'd like to request that a license agreement be applied to this project for protection.

**Comment by coderjun** [comment]
@jonnybach Missed this earlier. I will investigate this as well.

**Comment by jonnybach** [comment]
No problem, thank you!

**Comment by rmigneco** [comment]
@coderjun Just following up on this discussion, are there any plans to add a license agreement to this project?

I noticed some of the other parsing libraries have the MIT license, e.g. https://github.com/realeyes-media/scte35-kotlin/blob/master/LICENSE

Thanks

**Comment by coderjun** [comment]
Hi @rmigneco  - I think adding the agreement was missed. For now you can assume it'd be MIT or Apache 2 if that helps. Will take a note to have the team add one once there's some bandwidth.

**Comment by rmigneco** [comment]
@coderjun awesome - thanks

**Comment by coderjun** [comment]
@rmigneco license has been merged. Thanks!
